var schools = ("Alama Ace Unique Baptist");
console.log(schools);
document.write(schools);
var length = 10;
var breadth = 5;
var area = length*breadth;
console.log(area);
document.write("<br>");
document.write(area);
var base = 12;
var height = 2;
var linebreak = "<br>";
var area = (base * height)/2;
console.log(area);
document.write(linebreak);
document.write(area);
var firstname ="Peter";
var lastname ="Akobe";
var fullname; 
fullname = firstname + ' ' + lastname;
console.log(fullname);